# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/williamniemiec/Documents/workspace/ufrgs/PokeMaze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/williamniemiec/Documents/workspace/ufrgs/PokeMaze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/williamniemiec/Documents/workspace/ufrgs/PokeMaze/CMakeFiles /home/williamniemiec/Documents/workspace/ufrgs/PokeMaze/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/williamniemiec/Documents/workspace/ufrgs/PokeMaze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pokemaze

# Build rule for target.
pokemaze: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pokemaze
.PHONY : pokemaze

# fast build rule for target.
pokemaze/fast:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/build
.PHONY : pokemaze/fast

#=============================================================================
# Target rules for targets named scheduler_src

# Build rule for target.
scheduler_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scheduler_src
.PHONY : scheduler_src

# fast build rule for target.
scheduler_src/fast:
	$(MAKE) -f CMakeFiles/scheduler_src.dir/build.make CMakeFiles/scheduler_src.dir/build
.PHONY : scheduler_src/fast

#=============================================================================
# Target rules for targets named tinyfiledialogs

# Build rule for target.
tinyfiledialogs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyfiledialogs
.PHONY : tinyfiledialogs

# fast build rule for target.
tinyfiledialogs/fast:
	$(MAKE) -f CMakeFiles/tinyfiledialogs.dir/build.make CMakeFiles/tinyfiledialogs.dir/build
.PHONY : tinyfiledialogs/fast

#=============================================================================
# Target rules for targets named obj_loader

# Build rule for target.
obj_loader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_loader
.PHONY : obj_loader

# fast build rule for target.
obj_loader/fast:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/build
.PHONY : obj_loader/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named consolex_src

# Build rule for target.
consolex_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consolex_src
.PHONY : consolex_src

# fast build rule for target.
consolex_src/fast:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/build
.PHONY : consolex_src/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f lib/glfw/CMakeFiles/uninstall.dir/build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/wave.dir/build.make lib/glfw/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/splitview.dir/build.make lib/glfw/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/simple.dir/build.make lib/glfw/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/particles.dir/build.make lib/glfw/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/heightmap.dir/build.make lib/glfw/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/gears.dir/build.make lib/glfw/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) -f lib/glfw/examples/CMakeFiles/boing.dir/build.make lib/glfw/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named consolex

# Build rule for target.
consolex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consolex
.PHONY : consolex

# fast build rule for target.
consolex/fast:
	$(MAKE) -f lib/consolex/CMakeFiles/consolex.dir/build.make lib/consolex/CMakeFiles/consolex.dir/build
.PHONY : consolex/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

lib/consolex/src/wniemiec/io/cpp/Consolex.o: lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/Consolex.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.o

lib/consolex/src/wniemiec/io/cpp/Consolex.i: lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/Consolex.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.i

lib/consolex/src/wniemiec/io/cpp/Consolex.s: lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/Consolex.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/Consolex.cpp.s

lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.o: lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.o

lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.i: lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.i

lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.s: lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.cpp.s

lib/consolex/src/wniemiec/io/cpp/InputConsolex.o: lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/InputConsolex.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.o

lib/consolex/src/wniemiec/io/cpp/InputConsolex.i: lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/InputConsolex.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.i

lib/consolex/src/wniemiec/io/cpp/InputConsolex.s: lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/InputConsolex.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/InputConsolex.cpp.s

lib/consolex/src/wniemiec/io/cpp/LogLevel.o: lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/LogLevel.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.o

lib/consolex/src/wniemiec/io/cpp/LogLevel.i: lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/LogLevel.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.i

lib/consolex/src/wniemiec/io/cpp/LogLevel.s: lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/LogLevel.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/LogLevel.cpp.s

lib/consolex/src/wniemiec/io/cpp/LogMessage.o: lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/LogMessage.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.o

lib/consolex/src/wniemiec/io/cpp/LogMessage.i: lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/LogMessage.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.i

lib/consolex/src/wniemiec/io/cpp/LogMessage.s: lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/LogMessage.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/LogMessage.cpp.s

lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.o: lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.o

lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.i: lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.i

lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.s: lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.cpp.s

lib/consolex/src/wniemiec/io/cpp/OutputConsolex.o: lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.o

.PHONY : lib/consolex/src/wniemiec/io/cpp/OutputConsolex.o

# target to build an object file
lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.o:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.o
.PHONY : lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.o

lib/consolex/src/wniemiec/io/cpp/OutputConsolex.i: lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.i

.PHONY : lib/consolex/src/wniemiec/io/cpp/OutputConsolex.i

# target to preprocess a source file
lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.i:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.i
.PHONY : lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.i

lib/consolex/src/wniemiec/io/cpp/OutputConsolex.s: lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.s

.PHONY : lib/consolex/src/wniemiec/io/cpp/OutputConsolex.s

# target to generate assembly for a file
lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.s:
	$(MAKE) -f CMakeFiles/consolex_src.dir/build.make CMakeFiles/consolex_src.dir/lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.s
.PHONY : lib/consolex/src/wniemiec/io/cpp/OutputConsolex.cpp.s

lib/obj_loader/glad.o: lib/obj_loader/glad.c.o

.PHONY : lib/obj_loader/glad.o

# target to build an object file
lib/obj_loader/glad.c.o:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/glad.c.o
.PHONY : lib/obj_loader/glad.c.o

lib/obj_loader/glad.i: lib/obj_loader/glad.c.i

.PHONY : lib/obj_loader/glad.i

# target to preprocess a source file
lib/obj_loader/glad.c.i:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/glad.c.i
.PHONY : lib/obj_loader/glad.c.i

lib/obj_loader/glad.s: lib/obj_loader/glad.c.s

.PHONY : lib/obj_loader/glad.s

# target to generate assembly for a file
lib/obj_loader/glad.c.s:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/glad.c.s
.PHONY : lib/obj_loader/glad.c.s

lib/obj_loader/stb_image.o: lib/obj_loader/stb_image.cpp.o

.PHONY : lib/obj_loader/stb_image.o

# target to build an object file
lib/obj_loader/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/stb_image.cpp.o
.PHONY : lib/obj_loader/stb_image.cpp.o

lib/obj_loader/stb_image.i: lib/obj_loader/stb_image.cpp.i

.PHONY : lib/obj_loader/stb_image.i

# target to preprocess a source file
lib/obj_loader/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/stb_image.cpp.i
.PHONY : lib/obj_loader/stb_image.cpp.i

lib/obj_loader/stb_image.s: lib/obj_loader/stb_image.cpp.s

.PHONY : lib/obj_loader/stb_image.s

# target to generate assembly for a file
lib/obj_loader/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/stb_image.cpp.s
.PHONY : lib/obj_loader/stb_image.cpp.s

lib/obj_loader/tiny_obj_loader.o: lib/obj_loader/tiny_obj_loader.cpp.o

.PHONY : lib/obj_loader/tiny_obj_loader.o

# target to build an object file
lib/obj_loader/tiny_obj_loader.cpp.o:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/tiny_obj_loader.cpp.o
.PHONY : lib/obj_loader/tiny_obj_loader.cpp.o

lib/obj_loader/tiny_obj_loader.i: lib/obj_loader/tiny_obj_loader.cpp.i

.PHONY : lib/obj_loader/tiny_obj_loader.i

# target to preprocess a source file
lib/obj_loader/tiny_obj_loader.cpp.i:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/tiny_obj_loader.cpp.i
.PHONY : lib/obj_loader/tiny_obj_loader.cpp.i

lib/obj_loader/tiny_obj_loader.s: lib/obj_loader/tiny_obj_loader.cpp.s

.PHONY : lib/obj_loader/tiny_obj_loader.s

# target to generate assembly for a file
lib/obj_loader/tiny_obj_loader.cpp.s:
	$(MAKE) -f CMakeFiles/obj_loader.dir/build.make CMakeFiles/obj_loader.dir/lib/obj_loader/tiny_obj_loader.cpp.s
.PHONY : lib/obj_loader/tiny_obj_loader.cpp.s

lib/scheduler/src/wniemiec/task/cpp/Scheduler.o: lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.o

.PHONY : lib/scheduler/src/wniemiec/task/cpp/Scheduler.o

# target to build an object file
lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/scheduler_src.dir/build.make CMakeFiles/scheduler_src.dir/lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.o
.PHONY : lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.o

lib/scheduler/src/wniemiec/task/cpp/Scheduler.i: lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.i

.PHONY : lib/scheduler/src/wniemiec/task/cpp/Scheduler.i

# target to preprocess a source file
lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/scheduler_src.dir/build.make CMakeFiles/scheduler_src.dir/lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.i
.PHONY : lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.i

lib/scheduler/src/wniemiec/task/cpp/Scheduler.s: lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.s

.PHONY : lib/scheduler/src/wniemiec/task/cpp/Scheduler.s

# target to generate assembly for a file
lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/scheduler_src.dir/build.make CMakeFiles/scheduler_src.dir/lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.s
.PHONY : lib/scheduler/src/wniemiec/task/cpp/Scheduler.cpp.s

lib/tinyfiledialogs/tinyfiledialogs.o: lib/tinyfiledialogs/tinyfiledialogs.c.o

.PHONY : lib/tinyfiledialogs/tinyfiledialogs.o

# target to build an object file
lib/tinyfiledialogs/tinyfiledialogs.c.o:
	$(MAKE) -f CMakeFiles/tinyfiledialogs.dir/build.make CMakeFiles/tinyfiledialogs.dir/lib/tinyfiledialogs/tinyfiledialogs.c.o
.PHONY : lib/tinyfiledialogs/tinyfiledialogs.c.o

lib/tinyfiledialogs/tinyfiledialogs.i: lib/tinyfiledialogs/tinyfiledialogs.c.i

.PHONY : lib/tinyfiledialogs/tinyfiledialogs.i

# target to preprocess a source file
lib/tinyfiledialogs/tinyfiledialogs.c.i:
	$(MAKE) -f CMakeFiles/tinyfiledialogs.dir/build.make CMakeFiles/tinyfiledialogs.dir/lib/tinyfiledialogs/tinyfiledialogs.c.i
.PHONY : lib/tinyfiledialogs/tinyfiledialogs.c.i

lib/tinyfiledialogs/tinyfiledialogs.s: lib/tinyfiledialogs/tinyfiledialogs.c.s

.PHONY : lib/tinyfiledialogs/tinyfiledialogs.s

# target to generate assembly for a file
lib/tinyfiledialogs/tinyfiledialogs.c.s:
	$(MAKE) -f CMakeFiles/tinyfiledialogs.dir/build.make CMakeFiles/tinyfiledialogs.dir/lib/tinyfiledialogs/tinyfiledialogs.c.s
.PHONY : lib/tinyfiledialogs/tinyfiledialogs.c.s

src/pokemaze/App.o: src/pokemaze/App.cpp.o

.PHONY : src/pokemaze/App.o

# target to build an object file
src/pokemaze/App.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/App.cpp.o
.PHONY : src/pokemaze/App.cpp.o

src/pokemaze/App.i: src/pokemaze/App.cpp.i

.PHONY : src/pokemaze/App.i

# target to preprocess a source file
src/pokemaze/App.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/App.cpp.i
.PHONY : src/pokemaze/App.cpp.i

src/pokemaze/App.s: src/pokemaze/App.cpp.s

.PHONY : src/pokemaze/App.s

# target to generate assembly for a file
src/pokemaze/App.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/App.cpp.s
.PHONY : src/pokemaze/App.cpp.s

src/pokemaze/controllers/ErrorController.o: src/pokemaze/controllers/ErrorController.cpp.o

.PHONY : src/pokemaze/controllers/ErrorController.o

# target to build an object file
src/pokemaze/controllers/ErrorController.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/ErrorController.cpp.o
.PHONY : src/pokemaze/controllers/ErrorController.cpp.o

src/pokemaze/controllers/ErrorController.i: src/pokemaze/controllers/ErrorController.cpp.i

.PHONY : src/pokemaze/controllers/ErrorController.i

# target to preprocess a source file
src/pokemaze/controllers/ErrorController.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/ErrorController.cpp.i
.PHONY : src/pokemaze/controllers/ErrorController.cpp.i

src/pokemaze/controllers/ErrorController.s: src/pokemaze/controllers/ErrorController.cpp.s

.PHONY : src/pokemaze/controllers/ErrorController.s

# target to generate assembly for a file
src/pokemaze/controllers/ErrorController.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/ErrorController.cpp.s
.PHONY : src/pokemaze/controllers/ErrorController.cpp.s

src/pokemaze/controllers/KeyboardController.o: src/pokemaze/controllers/KeyboardController.cpp.o

.PHONY : src/pokemaze/controllers/KeyboardController.o

# target to build an object file
src/pokemaze/controllers/KeyboardController.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/KeyboardController.cpp.o
.PHONY : src/pokemaze/controllers/KeyboardController.cpp.o

src/pokemaze/controllers/KeyboardController.i: src/pokemaze/controllers/KeyboardController.cpp.i

.PHONY : src/pokemaze/controllers/KeyboardController.i

# target to preprocess a source file
src/pokemaze/controllers/KeyboardController.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/KeyboardController.cpp.i
.PHONY : src/pokemaze/controllers/KeyboardController.cpp.i

src/pokemaze/controllers/KeyboardController.s: src/pokemaze/controllers/KeyboardController.cpp.s

.PHONY : src/pokemaze/controllers/KeyboardController.s

# target to generate assembly for a file
src/pokemaze/controllers/KeyboardController.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/KeyboardController.cpp.s
.PHONY : src/pokemaze/controllers/KeyboardController.cpp.s

src/pokemaze/controllers/MouseController.o: src/pokemaze/controllers/MouseController.cpp.o

.PHONY : src/pokemaze/controllers/MouseController.o

# target to build an object file
src/pokemaze/controllers/MouseController.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/MouseController.cpp.o
.PHONY : src/pokemaze/controllers/MouseController.cpp.o

src/pokemaze/controllers/MouseController.i: src/pokemaze/controllers/MouseController.cpp.i

.PHONY : src/pokemaze/controllers/MouseController.i

# target to preprocess a source file
src/pokemaze/controllers/MouseController.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/MouseController.cpp.i
.PHONY : src/pokemaze/controllers/MouseController.cpp.i

src/pokemaze/controllers/MouseController.s: src/pokemaze/controllers/MouseController.cpp.s

.PHONY : src/pokemaze/controllers/MouseController.s

# target to generate assembly for a file
src/pokemaze/controllers/MouseController.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/controllers/MouseController.cpp.s
.PHONY : src/pokemaze/controllers/MouseController.cpp.s

src/pokemaze/engine/Display.o: src/pokemaze/engine/Display.cpp.o

.PHONY : src/pokemaze/engine/Display.o

# target to build an object file
src/pokemaze/engine/Display.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Display.cpp.o
.PHONY : src/pokemaze/engine/Display.cpp.o

src/pokemaze/engine/Display.i: src/pokemaze/engine/Display.cpp.i

.PHONY : src/pokemaze/engine/Display.i

# target to preprocess a source file
src/pokemaze/engine/Display.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Display.cpp.i
.PHONY : src/pokemaze/engine/Display.cpp.i

src/pokemaze/engine/Display.s: src/pokemaze/engine/Display.cpp.s

.PHONY : src/pokemaze/engine/Display.s

# target to generate assembly for a file
src/pokemaze/engine/Display.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Display.cpp.s
.PHONY : src/pokemaze/engine/Display.cpp.s

src/pokemaze/engine/Engine.o: src/pokemaze/engine/Engine.cpp.o

.PHONY : src/pokemaze/engine/Engine.o

# target to build an object file
src/pokemaze/engine/Engine.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Engine.cpp.o
.PHONY : src/pokemaze/engine/Engine.cpp.o

src/pokemaze/engine/Engine.i: src/pokemaze/engine/Engine.cpp.i

.PHONY : src/pokemaze/engine/Engine.i

# target to preprocess a source file
src/pokemaze/engine/Engine.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Engine.cpp.i
.PHONY : src/pokemaze/engine/Engine.cpp.i

src/pokemaze/engine/Engine.s: src/pokemaze/engine/Engine.cpp.s

.PHONY : src/pokemaze/engine/Engine.s

# target to generate assembly for a file
src/pokemaze/engine/Engine.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Engine.cpp.s
.PHONY : src/pokemaze/engine/Engine.cpp.s

src/pokemaze/engine/Renderer.o: src/pokemaze/engine/Renderer.cpp.o

.PHONY : src/pokemaze/engine/Renderer.o

# target to build an object file
src/pokemaze/engine/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Renderer.cpp.o
.PHONY : src/pokemaze/engine/Renderer.cpp.o

src/pokemaze/engine/Renderer.i: src/pokemaze/engine/Renderer.cpp.i

.PHONY : src/pokemaze/engine/Renderer.i

# target to preprocess a source file
src/pokemaze/engine/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Renderer.cpp.i
.PHONY : src/pokemaze/engine/Renderer.cpp.i

src/pokemaze/engine/Renderer.s: src/pokemaze/engine/Renderer.cpp.s

.PHONY : src/pokemaze/engine/Renderer.s

# target to generate assembly for a file
src/pokemaze/engine/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/Renderer.cpp.s
.PHONY : src/pokemaze/engine/Renderer.cpp.s

src/pokemaze/engine/projection/OrthographicProjection.o: src/pokemaze/engine/projection/OrthographicProjection.cpp.o

.PHONY : src/pokemaze/engine/projection/OrthographicProjection.o

# target to build an object file
src/pokemaze/engine/projection/OrthographicProjection.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/OrthographicProjection.cpp.o
.PHONY : src/pokemaze/engine/projection/OrthographicProjection.cpp.o

src/pokemaze/engine/projection/OrthographicProjection.i: src/pokemaze/engine/projection/OrthographicProjection.cpp.i

.PHONY : src/pokemaze/engine/projection/OrthographicProjection.i

# target to preprocess a source file
src/pokemaze/engine/projection/OrthographicProjection.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/OrthographicProjection.cpp.i
.PHONY : src/pokemaze/engine/projection/OrthographicProjection.cpp.i

src/pokemaze/engine/projection/OrthographicProjection.s: src/pokemaze/engine/projection/OrthographicProjection.cpp.s

.PHONY : src/pokemaze/engine/projection/OrthographicProjection.s

# target to generate assembly for a file
src/pokemaze/engine/projection/OrthographicProjection.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/OrthographicProjection.cpp.s
.PHONY : src/pokemaze/engine/projection/OrthographicProjection.cpp.s

src/pokemaze/engine/projection/PerspectiveProjection.o: src/pokemaze/engine/projection/PerspectiveProjection.cpp.o

.PHONY : src/pokemaze/engine/projection/PerspectiveProjection.o

# target to build an object file
src/pokemaze/engine/projection/PerspectiveProjection.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/PerspectiveProjection.cpp.o
.PHONY : src/pokemaze/engine/projection/PerspectiveProjection.cpp.o

src/pokemaze/engine/projection/PerspectiveProjection.i: src/pokemaze/engine/projection/PerspectiveProjection.cpp.i

.PHONY : src/pokemaze/engine/projection/PerspectiveProjection.i

# target to preprocess a source file
src/pokemaze/engine/projection/PerspectiveProjection.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/PerspectiveProjection.cpp.i
.PHONY : src/pokemaze/engine/projection/PerspectiveProjection.cpp.i

src/pokemaze/engine/projection/PerspectiveProjection.s: src/pokemaze/engine/projection/PerspectiveProjection.cpp.s

.PHONY : src/pokemaze/engine/projection/PerspectiveProjection.s

# target to generate assembly for a file
src/pokemaze/engine/projection/PerspectiveProjection.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/PerspectiveProjection.cpp.s
.PHONY : src/pokemaze/engine/projection/PerspectiveProjection.cpp.s

src/pokemaze/engine/projection/Projection.o: src/pokemaze/engine/projection/Projection.cpp.o

.PHONY : src/pokemaze/engine/projection/Projection.o

# target to build an object file
src/pokemaze/engine/projection/Projection.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/Projection.cpp.o
.PHONY : src/pokemaze/engine/projection/Projection.cpp.o

src/pokemaze/engine/projection/Projection.i: src/pokemaze/engine/projection/Projection.cpp.i

.PHONY : src/pokemaze/engine/projection/Projection.i

# target to preprocess a source file
src/pokemaze/engine/projection/Projection.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/Projection.cpp.i
.PHONY : src/pokemaze/engine/projection/Projection.cpp.i

src/pokemaze/engine/projection/Projection.s: src/pokemaze/engine/projection/Projection.cpp.s

.PHONY : src/pokemaze/engine/projection/Projection.s

# target to generate assembly for a file
src/pokemaze/engine/projection/Projection.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/projection/Projection.cpp.s
.PHONY : src/pokemaze/engine/projection/Projection.cpp.s

src/pokemaze/engine/text/TextRender.o: src/pokemaze/engine/text/TextRender.cpp.o

.PHONY : src/pokemaze/engine/text/TextRender.o

# target to build an object file
src/pokemaze/engine/text/TextRender.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/text/TextRender.cpp.o
.PHONY : src/pokemaze/engine/text/TextRender.cpp.o

src/pokemaze/engine/text/TextRender.i: src/pokemaze/engine/text/TextRender.cpp.i

.PHONY : src/pokemaze/engine/text/TextRender.i

# target to preprocess a source file
src/pokemaze/engine/text/TextRender.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/text/TextRender.cpp.i
.PHONY : src/pokemaze/engine/text/TextRender.cpp.i

src/pokemaze/engine/text/TextRender.s: src/pokemaze/engine/text/TextRender.cpp.s

.PHONY : src/pokemaze/engine/text/TextRender.s

# target to generate assembly for a file
src/pokemaze/engine/text/TextRender.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/engine/text/TextRender.cpp.s
.PHONY : src/pokemaze/engine/text/TextRender.cpp.s

src/pokemaze/models/BoundingBox.o: src/pokemaze/models/BoundingBox.cpp.o

.PHONY : src/pokemaze/models/BoundingBox.o

# target to build an object file
src/pokemaze/models/BoundingBox.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/BoundingBox.cpp.o
.PHONY : src/pokemaze/models/BoundingBox.cpp.o

src/pokemaze/models/BoundingBox.i: src/pokemaze/models/BoundingBox.cpp.i

.PHONY : src/pokemaze/models/BoundingBox.i

# target to preprocess a source file
src/pokemaze/models/BoundingBox.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/BoundingBox.cpp.i
.PHONY : src/pokemaze/models/BoundingBox.cpp.i

src/pokemaze/models/BoundingBox.s: src/pokemaze/models/BoundingBox.cpp.s

.PHONY : src/pokemaze/models/BoundingBox.s

# target to generate assembly for a file
src/pokemaze/models/BoundingBox.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/BoundingBox.cpp.s
.PHONY : src/pokemaze/models/BoundingBox.cpp.s

src/pokemaze/models/Point.o: src/pokemaze/models/Point.cpp.o

.PHONY : src/pokemaze/models/Point.o

# target to build an object file
src/pokemaze/models/Point.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/Point.cpp.o
.PHONY : src/pokemaze/models/Point.cpp.o

src/pokemaze/models/Point.i: src/pokemaze/models/Point.cpp.i

.PHONY : src/pokemaze/models/Point.i

# target to preprocess a source file
src/pokemaze/models/Point.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/Point.cpp.i
.PHONY : src/pokemaze/models/Point.cpp.i

src/pokemaze/models/Point.s: src/pokemaze/models/Point.cpp.s

.PHONY : src/pokemaze/models/Point.s

# target to generate assembly for a file
src/pokemaze/models/Point.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/Point.cpp.s
.PHONY : src/pokemaze/models/Point.cpp.s

src/pokemaze/models/SceneObject.o: src/pokemaze/models/SceneObject.cpp.o

.PHONY : src/pokemaze/models/SceneObject.o

# target to build an object file
src/pokemaze/models/SceneObject.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/SceneObject.cpp.o
.PHONY : src/pokemaze/models/SceneObject.cpp.o

src/pokemaze/models/SceneObject.i: src/pokemaze/models/SceneObject.cpp.i

.PHONY : src/pokemaze/models/SceneObject.i

# target to preprocess a source file
src/pokemaze/models/SceneObject.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/SceneObject.cpp.i
.PHONY : src/pokemaze/models/SceneObject.cpp.i

src/pokemaze/models/SceneObject.s: src/pokemaze/models/SceneObject.cpp.s

.PHONY : src/pokemaze/models/SceneObject.s

# target to generate assembly for a file
src/pokemaze/models/SceneObject.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/SceneObject.cpp.s
.PHONY : src/pokemaze/models/SceneObject.cpp.s

src/pokemaze/models/camera/Camera.o: src/pokemaze/models/camera/Camera.cpp.o

.PHONY : src/pokemaze/models/camera/Camera.o

# target to build an object file
src/pokemaze/models/camera/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/Camera.cpp.o
.PHONY : src/pokemaze/models/camera/Camera.cpp.o

src/pokemaze/models/camera/Camera.i: src/pokemaze/models/camera/Camera.cpp.i

.PHONY : src/pokemaze/models/camera/Camera.i

# target to preprocess a source file
src/pokemaze/models/camera/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/Camera.cpp.i
.PHONY : src/pokemaze/models/camera/Camera.cpp.i

src/pokemaze/models/camera/Camera.s: src/pokemaze/models/camera/Camera.cpp.s

.PHONY : src/pokemaze/models/camera/Camera.s

# target to generate assembly for a file
src/pokemaze/models/camera/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/Camera.cpp.s
.PHONY : src/pokemaze/models/camera/Camera.cpp.s

src/pokemaze/models/camera/FreeCamera.o: src/pokemaze/models/camera/FreeCamera.cpp.o

.PHONY : src/pokemaze/models/camera/FreeCamera.o

# target to build an object file
src/pokemaze/models/camera/FreeCamera.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/FreeCamera.cpp.o
.PHONY : src/pokemaze/models/camera/FreeCamera.cpp.o

src/pokemaze/models/camera/FreeCamera.i: src/pokemaze/models/camera/FreeCamera.cpp.i

.PHONY : src/pokemaze/models/camera/FreeCamera.i

# target to preprocess a source file
src/pokemaze/models/camera/FreeCamera.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/FreeCamera.cpp.i
.PHONY : src/pokemaze/models/camera/FreeCamera.cpp.i

src/pokemaze/models/camera/FreeCamera.s: src/pokemaze/models/camera/FreeCamera.cpp.s

.PHONY : src/pokemaze/models/camera/FreeCamera.s

# target to generate assembly for a file
src/pokemaze/models/camera/FreeCamera.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/FreeCamera.cpp.s
.PHONY : src/pokemaze/models/camera/FreeCamera.cpp.s

src/pokemaze/models/camera/LookAtCamera.o: src/pokemaze/models/camera/LookAtCamera.cpp.o

.PHONY : src/pokemaze/models/camera/LookAtCamera.o

# target to build an object file
src/pokemaze/models/camera/LookAtCamera.cpp.o:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/LookAtCamera.cpp.o
.PHONY : src/pokemaze/models/camera/LookAtCamera.cpp.o

src/pokemaze/models/camera/LookAtCamera.i: src/pokemaze/models/camera/LookAtCamera.cpp.i

.PHONY : src/pokemaze/models/camera/LookAtCamera.i

# target to preprocess a source file
src/pokemaze/models/camera/LookAtCamera.cpp.i:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/LookAtCamera.cpp.i
.PHONY : src/pokemaze/models/camera/LookAtCamera.cpp.i

src/pokemaze/models/camera/LookAtCamera.s: src/pokemaze/models/camera/LookAtCamera.cpp.s

.PHONY : src/pokemaze/models/camera/LookAtCamera.s

# target to generate assembly for a file
src/pokemaze/models/camera/LookAtCamera.cpp.s:
	$(MAKE) -f CMakeFiles/pokemaze.dir/build.make CMakeFiles/pokemaze.dir/src/pokemaze/models/camera/LookAtCamera.cpp.s
.PHONY : src/pokemaze/models/camera/LookAtCamera.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... pokemaze"
	@echo "... install/local"
	@echo "... scheduler_src"
	@echo "... tinyfiledialogs"
	@echo "... obj_loader"
	@echo "... release"
	@echo "... clean-all"
	@echo "... debug"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... consolex_src"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... wave"
	@echo "... splitview"
	@echo "... simple"
	@echo "... particles"
	@echo "... heightmap"
	@echo "... gears"
	@echo "... boing"
	@echo "... consolex"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... lib/consolex/src/wniemiec/io/cpp/Consolex.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/Consolex.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/Consolex.s"
	@echo "... lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/HistoryConsolex.s"
	@echo "... lib/consolex/src/wniemiec/io/cpp/InputConsolex.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/InputConsolex.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/InputConsolex.s"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LogLevel.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LogLevel.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LogLevel.s"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LogMessage.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LogMessage.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LogMessage.s"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/LoggerConsolex.s"
	@echo "... lib/consolex/src/wniemiec/io/cpp/OutputConsolex.o"
	@echo "... lib/consolex/src/wniemiec/io/cpp/OutputConsolex.i"
	@echo "... lib/consolex/src/wniemiec/io/cpp/OutputConsolex.s"
	@echo "... lib/obj_loader/glad.o"
	@echo "... lib/obj_loader/glad.i"
	@echo "... lib/obj_loader/glad.s"
	@echo "... lib/obj_loader/stb_image.o"
	@echo "... lib/obj_loader/stb_image.i"
	@echo "... lib/obj_loader/stb_image.s"
	@echo "... lib/obj_loader/tiny_obj_loader.o"
	@echo "... lib/obj_loader/tiny_obj_loader.i"
	@echo "... lib/obj_loader/tiny_obj_loader.s"
	@echo "... lib/scheduler/src/wniemiec/task/cpp/Scheduler.o"
	@echo "... lib/scheduler/src/wniemiec/task/cpp/Scheduler.i"
	@echo "... lib/scheduler/src/wniemiec/task/cpp/Scheduler.s"
	@echo "... lib/tinyfiledialogs/tinyfiledialogs.o"
	@echo "... lib/tinyfiledialogs/tinyfiledialogs.i"
	@echo "... lib/tinyfiledialogs/tinyfiledialogs.s"
	@echo "... src/pokemaze/App.o"
	@echo "... src/pokemaze/App.i"
	@echo "... src/pokemaze/App.s"
	@echo "... src/pokemaze/controllers/ErrorController.o"
	@echo "... src/pokemaze/controllers/ErrorController.i"
	@echo "... src/pokemaze/controllers/ErrorController.s"
	@echo "... src/pokemaze/controllers/KeyboardController.o"
	@echo "... src/pokemaze/controllers/KeyboardController.i"
	@echo "... src/pokemaze/controllers/KeyboardController.s"
	@echo "... src/pokemaze/controllers/MouseController.o"
	@echo "... src/pokemaze/controllers/MouseController.i"
	@echo "... src/pokemaze/controllers/MouseController.s"
	@echo "... src/pokemaze/engine/Display.o"
	@echo "... src/pokemaze/engine/Display.i"
	@echo "... src/pokemaze/engine/Display.s"
	@echo "... src/pokemaze/engine/Engine.o"
	@echo "... src/pokemaze/engine/Engine.i"
	@echo "... src/pokemaze/engine/Engine.s"
	@echo "... src/pokemaze/engine/Renderer.o"
	@echo "... src/pokemaze/engine/Renderer.i"
	@echo "... src/pokemaze/engine/Renderer.s"
	@echo "... src/pokemaze/engine/projection/OrthographicProjection.o"
	@echo "... src/pokemaze/engine/projection/OrthographicProjection.i"
	@echo "... src/pokemaze/engine/projection/OrthographicProjection.s"
	@echo "... src/pokemaze/engine/projection/PerspectiveProjection.o"
	@echo "... src/pokemaze/engine/projection/PerspectiveProjection.i"
	@echo "... src/pokemaze/engine/projection/PerspectiveProjection.s"
	@echo "... src/pokemaze/engine/projection/Projection.o"
	@echo "... src/pokemaze/engine/projection/Projection.i"
	@echo "... src/pokemaze/engine/projection/Projection.s"
	@echo "... src/pokemaze/engine/text/TextRender.o"
	@echo "... src/pokemaze/engine/text/TextRender.i"
	@echo "... src/pokemaze/engine/text/TextRender.s"
	@echo "... src/pokemaze/models/BoundingBox.o"
	@echo "... src/pokemaze/models/BoundingBox.i"
	@echo "... src/pokemaze/models/BoundingBox.s"
	@echo "... src/pokemaze/models/Point.o"
	@echo "... src/pokemaze/models/Point.i"
	@echo "... src/pokemaze/models/Point.s"
	@echo "... src/pokemaze/models/SceneObject.o"
	@echo "... src/pokemaze/models/SceneObject.i"
	@echo "... src/pokemaze/models/SceneObject.s"
	@echo "... src/pokemaze/models/camera/Camera.o"
	@echo "... src/pokemaze/models/camera/Camera.i"
	@echo "... src/pokemaze/models/camera/Camera.s"
	@echo "... src/pokemaze/models/camera/FreeCamera.o"
	@echo "... src/pokemaze/models/camera/FreeCamera.i"
	@echo "... src/pokemaze/models/camera/FreeCamera.s"
	@echo "... src/pokemaze/models/camera/LookAtCamera.o"
	@echo "... src/pokemaze/models/camera/LookAtCamera.i"
	@echo "... src/pokemaze/models/camera/LookAtCamera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

