if(EXISTS "C:/Users/william/Desktop/CG/nRenderer/lib/scheduler/scheduler[1]_tests.cmake")
  include("C:/Users/william/Desktop/CG/nRenderer/lib/scheduler/scheduler[1]_tests.cmake")
else()
  add_test(scheduler_NOT_BUILT scheduler_NOT_BUILT)
endif()
